# Using container-based infrastructure
sudo: false

# 'bash' will define a generic environment without interfering environment
# settings like "CC=gcc"
language: bash

# Only build the master branch
branches:
    only:
        - 166MMX-patch-1

# Installing needed dependencies
addons:
    apt:
        sources:
            - debian-sid    # Grab shellcheck from the Debian repo (o_O)
        packages:
            - shellcheck

# Building the standard samples
script:
    - shellcheck bootstrap scripts/functions
    - find scripts -type f -name '*.sh' -exec shellcheck '{}' ';'
    - find scripts -type f ! -name '*.sh' -exec file '{}'  '|' awk '-F:' '/bash/ {print $1}' '|' xargs -l -i 'shellcheck "{}"' ';'
    #- bash -c 'shopt -s globstar; shellcheck **/*.{sh,bash}'
    #- . ./.travis.sh      # Load the travis environment
    #- ct-ng $CT_SAMPLE    # Configure the build
    #- ct-ng_travis_build  # Build the sample
